export const orderElements = {
    linkMyaccount: '#nav-link-accountList',
    inputEmail: "#ap_email",
    submitEmail: "#continue",
    inputPassword: "#password",
    submitPassword: "#signInSubmit",
    nameAccount: "#nav-link-accountList-nav-line-1",
    containerMyaccount: ".a-container",
    inputSearchSku: "#twotabsearchtextbox",
    buttonSubmitSearch: "#nav-search-submit-button",
    divDescripitionSku: '[data-cy="title-recipe"] h2 > .a-link-normal > span',
    clickAddToCart: "#add-to-cart-button",
    goToCart: '[data-feature-id="proceed-to-checkout-action"]',
    confirmAdress: "#orderSummaryPrimaryActionBtn",
    paymentBill: "span:contains('Boleto')",
    selectRadioBoleto: '[type="radio"]',
    confirmPayment: "input:has(+ span:contains('Usar esta forma de pagamento'))",
    buttonCloseOrder: '#bottomSubmitOrderButtonId',
    duplicateValidateButton: '.a-button-primary > .a-button-inner > .a-button-text'
}
